services:
 mariadb:
  build: ./requirements/mariadb
  container_name: mariadb
  restart: always
  env_file:
   - .env
  ports:
   - "3306:3306"
  volumes:
   - mariadb_data:/var/lib/mysql
  networks:
  - inception_net

volumes:
 mariadb_data:

networks:
 inception_net:
