services:

 nginx:
  build: ./requirements/nginx
  container_name: nginx
  restart: always
  ports:
   - "443:443"
  volumes:
   - static_website:/var/www/html
  networks:
   - inception_net

 mariadb:
  build: ./requirements/mariadb
  container_name: mariadb
  restart: always
  env_file:
   - .env
  ports:
   - "3306:3306"
  volumes:
   - mariadb_data:/var/lib/mysql
  networks:
  - inception_net

volumes:
 mariadb_data:
 static_website:

networks:
 inception_net:
