volumes:
 wordpress:
   driver: local
   driver_opts:
    type: none
    o: bind
    device: /home/mito/data/wordpress

 mariadb:
   driver: local
   driver_opts:
    type: none
    o: bind
    device: /home/mito/data/mariadb

networks:
 inception_net:
#  name: inception_net
  driver: bridge

services:
 mariadb:
  build: ./requirements/mariadb
  container_name: mariadb
  restart: always
  image: mariadb:mito
  expose:
   - 3306
  env_file:
   - .env
  volumes:
   - mariadb:/var/lib/mysql
  networks:
  - inception_net

 nginx:
  build: ./requirements/nginx
  container_name: nginx
  image: nginx:mito
  restart: always
  env_file:
   - .env
  ports:
   - "443:443"
  volumes:
   - wordpress:/var/www/html
  networks:
   - inception_net
  depends_on:
   - wordpress

 wordpress:
  build: ./requirements/wordpress
  container_name: wordpress
  restart: always
  image: wordpress:mito
  expose:
   - "9000"
  env_file:
   - .env
  volumes:
   - wordpress:/var/www/html
  networks:
   - inception_net
  depends_on:
   - mariadb
